machine-74:
  ip: "192.168.98.74"
  user: jingxiang
  passwd: "1111"
  numa_type: 1
  machine_type: common
  threads_per_socket: 36
  socket_count: 2
  available_nic: [0, 1]
    
machine-74_dpu:
  ip: "192.168.98.144"
  machine_type: dpu
  user: ubuntu
  passwd: ddstgogo
  numa_type: 3
  threads_per_socket: 8
  socket_count: 1
  available_nic: [1]
    
  
machine_71:
  ip: "192.168.98.71"
  machine_type: common
  user: jingxiang
  passwd: "1111"
  numa_type: 1
  threads_per_socket: 36
  socket_count: 2
  available_nic: [0, 1]
  